# Cell 1: Install Required Libraries

In [1]:
!pip install datasets pandas transformers torch

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.10.0+cu128)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.29.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (1.11.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers) (0.24.0)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch) (3.1.6)
Requirement already satisfied: cuda-bindings==12.9.4 in /usr/local/lib/python3.12/dist-packages (from torch) (12.9.4)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.4.5 in /usr/local/lib/python3.12/dist-packages (from torch) (3.4.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.13.1.3)
Requirement already satisfied: triton==3.6.0 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.0)
Requirement already satisfied: cuda-pathfinder~=1.1 in /usr/local/lib/python3.12/dist-packages (from cuda-bindings==12.9.4->torch) (1.5.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.13.5)
Requirement already satisfied: hf-xet<2.0.0,>=1.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (1.4.3)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (0.28.1)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (0.24.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.4.22)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch) (3.0.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (4.13.0)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.24.0->datasets) (0.16.0)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.24.0->datasets) (8.3.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.24.0->datasets) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.24.0->datasets) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->huggingface-hub>=0.24.0->datasets) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.24.0->datasets) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer->huggingface-hub>=0.24.0->datasets) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer->huggingface-hub>=0.24.0->datasets) (0.1.2)

# Cell 2: Import Dependencies

In [2]:
import pandas as pd
from datasets import load_dataset

# Set pandas display options to easily read long text strings in the notebook
pd.set_option('display.max_colwidth', None)

# Cell 3: Import Hausa dataset

In [3]:
# Load the BRIGHTER dataset specifically for the Hausa configuration ("hau")
hausa_dataset = load_dataset("brighter-dataset/BRIGHTER-emotion-categories", "hau")

# View the structure of the downloaded Hausa dataset
print("Hausa Dataset Splits:")
print(hausa_dataset)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:93: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

README.md: 0.00B [00:00, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

hau/train-00000-of-00001.parquet:   0%|          | 0.00/144k [00:00<?, ?B/s]

hau/dev-00000-of-00001.parquet:   0%|          | 0.00/31.3k [00:00<?, ?B/s]

hau/test-00000-of-00001.parquet:   0%|          | 0.00/83.7k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/2145 [00:00<?, ? examples/s]

Generating dev split:   0%|          | 0/712 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/2160 [00:00<?, ? examples/s]

Hausa Dataset Splits:
DatasetDict({
    train: Dataset({
        features: ['id', 'text', 'anger', 'disgust', 'fear', 'joy', 'sadness', 'surprise', 'emotions'],
        num_rows: 2145
    })
    dev: Dataset({
        features: ['id', 'text', 'anger', 'disgust', 'fear', 'joy', 'sadness', 'surprise', 'emotions'],
        num_rows: 712
    })
    test: Dataset({
        features: ['id', 'text', 'anger', 'disgust', 'fear', 'joy', 'sadness', 'surprise', 'emotions'],
        num_rows: 2160
    })
})

# Cell 4: Inspect data  
Since hausa_dataset is already filtered, you can jump straight to inspecting it:

In [4]:
# Convert the Hausa training split to a Pandas DataFrame for visual inspection
df_hausa_train = hausa_dataset['train'].to_pandas()

# Display the first 5 rows
df_hausa_train.head()

,id,text,anger,disgust,fear,joy,sadness,surprise,emotions
0,hau_train_track_a_00001,"kotu ta yi hukunci kan shari'ar zaben dan majalisar pdp, ta yi hukuncin bazata",0,0,0,0,0,1,[surprise]
1,hau_train_track_a_00002,"toh fah inji 'yan magana suka ce """"""""ana wata ga wata""""""""🤣😂",0,0,0,0,0,1,[surprise]
2,hau_train_track_a_00003,bincike ya nuna yan najeriya sun fi damuwa da rashin tsaro da talauci fiye da korona,0,0,1,0,1,0,"[fear, sadness]"
3,hau_train_track_a_00004,kwamishina ya musanta rahoton masari ya cire kusan miliyan n500m don tarban buhari,0,0,0,0,0,0,[]
4,hau_train_track_a_00005,innalillahi wa inna ilaihir raji'un: allah ya yi wa mahaifiyar halima atete rasuwa,0,0,0,0,1,0,[sadness]

# Cell 5: Basic Text Cleaning  
Even though the BRIGHTER dataset is generally high-quality, it is always a good idea to ensure there are no lingering URLs, excessive spaces, or weird formatting artifacts before passing the text to a transformer model.

In [5]:
import re

def clean_text(example):
    text = example['text']
    # Remove URLs if any exist
    text = re.sub(r'http\S+|www\S+|https\S+', '', text, flags=re.MULTILINE)
    # Remove extra whitespaces
    text = text.strip()
    return {'text': text}

# Apply the cleaning function to all splits
hausa_dataset = hausa_dataset.map(clean_text)

print("Text cleaning complete!")

Map:   0%|          | 0/2145 [00:00<?, ? examples/s]

Map:   0%|          | 0/712 [00:00<?, ? examples/s]

Map:   0%|          | 0/2160 [00:00<?, ? examples/s]

Text cleaning complete!

# Cell 6: Formatting the Multilabel Target Vectors  
To train a multilabel model, the individual binary columns (anger, disgust, fear, joy, sadness, surprise) must be combined into a single array (vector) for each row. Furthermore, PyTorch's Binary Cross-Entropy loss requires these labels to be formatted as floats, not integers.

In [6]:
# Define the exact order of your emotion columns
emotion_cols = ['anger', 'disgust', 'fear', 'joy', 'sadness', 'surprise']

def format_labels(example):
    # Create a list of floats representing the presence (1.0) or absence (0.0) of each emotion
    labels = [float(example[col]) for col in emotion_cols]
    return {'labels': labels}

# Apply the label formatting to all splits
hausa_dataset = hausa_dataset.map(format_labels)

# Inspect the first row of the training set to verify the new 'labels' column
print("Original emotions list:", hausa_dataset['train'][0]['emotions'])
print("New target vector (labels):", hausa_dataset['train'][0]['labels'])

Map:   0%|          | 0/2145 [00:00<?, ? examples/s]

Map:   0%|          | 0/712 [00:00<?, ? examples/s]

Map:   0%|          | 0/2160 [00:00<?, ? examples/s]

Original emotions list: ['surprise']
New target vector (labels): [0.0, 0.0, 0.0, 0.0, 0.0, 1.0]

# Cell 7: Tokenization (Preparing for AfroXLMR / XLM-RoBERTa)  
Now that the text is clean and the labels are perfectly formatted, we need to convert the text into tokens (numbers) that the model can actually understand. We are using AfroXLMR. We will pull its specific tokenizer here.

In [7]:
from transformers import AutoTokenizer

# Load the tokenizer for AfroXLMR (or swap with "xlm-roberta-large" if preferred)
model_checkpoint = "Davlan/afro-xlmr-large"
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)

def tokenize_function(examples):
    # Tokenize the text, pad shorter sentences, and truncate longer ones to a max length
    return tokenizer(
        examples['text'],
        padding="max_length",
        truncation=True,
        max_length=128 # 128 is usually sufficient for tweets/short texts; increase to 256 or 512 if your texts are long paragraphs
    )

# Apply tokenization in batches (this is much faster)
tokenized_hausa = hausa_dataset.map(tokenize_function, batched=True)

# View the new columns added by the tokenizer
print("Columns after tokenization:", tokenized_hausa['train'].column_names)

config.json:   0%|          | 0.00/714 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/399 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

Map:   0%|          | 0/2145 [00:00<?, ? examples/s]

Map:   0%|          | 0/712 [00:00<?, ? examples/s]

Map:   0%|          | 0/2160 [00:00<?, ? examples/s]

Columns after tokenization: ['id', 'text', 'anger', 'disgust', 'fear', 'joy', 'sadness', 'surprise', 'emotions', 'labels', 'input_ids', 'attention_mask']

# Cell 8: Final Cleanup for PyTorch  
The Hugging Face Trainer expects only specific columns (input_ids, attention_mask, and labels). It will throw an error if we leave the raw string text or the old integer columns in the dataset during training.

In [8]:
# Define the columns we want to KEEP for training
columns_to_keep = ['input_ids', 'attention_mask', 'labels']

# Remove all other columns (like 'id', 'text', 'anger', 'joy', etc.)
tokenized_hausa.set_format(type='torch', columns=columns_to_keep)

print("Dataset is fully pre-processed and ready for PyTorch!")
print(tokenized_hausa['train'][0])

Dataset is fully pre-processed and ready for PyTorch!
{'labels': tensor([0., 0., 0., 0., 0., 1.]), 'input_ids': tensor([     0,   1975,     34,    308,  11180,  39545,   7700,    203, 152093,
            25,    147,     80,    776,    123, 185841,    915,     71,    254,
             4,    308,  11180,  39545,  78479,  12170,    102,      2,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1,      1,      1,      1,      1,      1,      1,      1,
             1,      1]), 'attention_mask': tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0])}

In [9]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)

In [10]:
# Check a sample
sample = tokenized_hausa['train'][0]
print(f"Labels type: {type(sample['labels'][0])}") # Should say <class 'torch.Tensor'>
print(f"Labels values: {sample['labels']}")       # Should look like tensor([0., 1., 0., ...])

Labels type: <class 'torch.Tensor'>
Labels values: tensor([0., 0., 0., 0., 0., 1.])

# Cell 9: Define the Evaluation Metrics  
Because this is a multilabel task, the model won't output a single probability. It will output "logits" (raw scores) for all 6 emotions. We need to pass these through a Sigmoid function and set a threshold (usually 0.5) to decide if an emotion is present (1) or not (0).

In [11]:
import numpy as np
import torch
from sklearn.metrics import f1_score, accuracy_score

def compute_metrics(eval_pred):
    logits, labels = eval_pred

    # Apply sigmoid activation to the raw logits to get probabilities between 0 and 1
    sigmoid = torch.nn.Sigmoid()
    probs = sigmoid(torch.Tensor(logits))

    # Convert probabilities to binary predictions using a 0.5 threshold
    y_pred = np.zeros(probs.shape)
    y_pred[np.where(probs >= 0.3)] = 1

    # Calculate your core metrics
    f1_macro = f1_score(labels, y_pred, average='macro') # Your main project metric!
    f1_micro = f1_score(labels, y_pred, average='micro')
    accuracy = accuracy_score(labels, y_pred)

    return {
        'f1_macro': f1_macro,
        'f1_micro': f1_micro,
        'accuracy': accuracy
    }
print("Metrics defined!")

Metrics defined!

# Cell 10: Initialize the AfroXLMR Model  
We will now load the pre-trained transformer and add a classification head on top of it designed specifically for 6 labels. Setting problem_type="multi_label_classification" automatically configures the model to use the Binary Cross-Entropy (BCE) loss function we specified in our methodology.

In [12]:
from transformers import AutoModelForSequenceClassification

# We have 6 specific emotion categories
num_labels = 6
model_checkpoint = "Davlan/afro-xlmr-base"

model = AutoModelForSequenceClassification.from_pretrained(
    model_checkpoint,
    num_labels=num_labels,
    problem_type="multi_label_classification",
    ignore_mismatched_sizes=True # Best practice when initializing a new classification head
)
print("AfroXLMR model loaded and configured for multilabel classification!")

config.json:   0%|          | 0.00/707 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForSequenceClassification LOAD REPORT from: Davlan/afro-xlmr-base
Key                             | Status     |
--------------------------------+------------+-
lm_head.dense.bias              | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
classifier.out_proj.bias        | MISSING    |
classifier.dense.bias           | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

AfroXLMR model loaded and configured for multilabel classification!

# Cell 11: Set up the Training Arguments and Trainer  
The Trainer handles the heavy lifting of the PyTorch training loop. We will configure it to train for a few epochs and evaluate itself using the validation set after every epoch.

In [13]:
from transformers import TrainingArguments, Trainer

# Check the exact name of your validation split (sometimes it's 'dev' or 'validation')
val_split_name = 'validation' if 'validation' in tokenized_hausa else 'dev'

training_args = TrainingArguments(
    output_dir='./hausa_baseline_results',
    eval_strategy="epoch",          # Evaluate every epoch
    save_strategy="epoch",          # ADD THIS: Save every epoch so they match
    learning_rate=5e-5,
    lr_scheduler_type="cosine",
    per_device_train_batch_size=16,
    num_train_epochs=10,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="f1_macro"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_hausa['train'],
    eval_dataset=tokenized_hausa[val_split_name],
    compute_metrics=compute_metrics
)
print("Trainer successfully initialized!")

Trainer successfully initialized!

# Cell 12: Train and Evaluate the Baseline!  
Running this cell will start the training process. Warning: Depending on your hardware (CPU vs. GPU), this step can take some time.

In [14]:
# 1. Start the training loop
print("Starting training...")
trainer.train()

# 2. Evaluate the model on the unseen TEST set to get your final Baseline metrics
print("\nEvaluating on Test Set...")
baseline_results = trainer.evaluate(tokenized_hausa['test'])

print("\n=== FINAL HAUSA BASELINE RESULTS ===")
print(f"F1-Macro: {baseline_results['eval_f1_macro']:.4f}")
print(f"F1-Micro: {baseline_results['eval_f1_micro']:.4f}")
print(f"Accuracy: {baseline_results['eval_accuracy']:.4f}")

Starting training...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.weight', 'roberta.embeddings.LayerNorm.bias', 'roberta.encoder.layer.0.attention.output.LayerNorm.weight', 'roberta.encoder.layer.0.attention.output.LayerNorm.bias', 'roberta.encoder.layer.0.output.LayerNorm.weight', 'roberta.encoder.layer.0.output.LayerNorm.bias', 'roberta.encoder.layer.1.attention.output.LayerNorm.weight', 'roberta.encoder.layer.1.attention.output.LayerNorm.bias', 'roberta.encoder.layer.1.output.LayerNorm.weight', 'roberta.encoder.layer.1.output.LayerNorm.bias', 'roberta.encoder.layer.2.attention.output.LayerNorm.weight', 'roberta.encoder.layer.2.attention.output.LayerNorm.bias', 'roberta.encoder.layer.2.output.LayerNorm.weight', 'roberta.encoder.layer.2.output.LayerNorm.bias', 'roberta.encoder.layer.3.attention.output.LayerNorm.weight', 'roberta.encoder.layer.3.attention.output.LayerNorm.bias', 'roberta.encoder.layer.3.output.LayerNorm.weight', 'roberta.encoder.layer.3.output.LayerNorm.bias', 'roberta.encoder.layer.4.attention.output.LayerNorm.weight', 'roberta.encoder.layer.4.attention.output.LayerNorm.bias', 'roberta.encoder.layer.4.output.LayerNorm.weight', 'roberta.encoder.layer.4.output.LayerNorm.bias', 'roberta.encoder.layer.5.attention.output.LayerNorm.weight', 'roberta.encoder.layer.5.attention.output.LayerNorm.bias', 'roberta.encoder.layer.5.output.LayerNorm.weight', 'roberta.encoder.layer.5.output.LayerNorm.bias', 'roberta.encoder.layer.6.attention.output.LayerNorm.weight', 'roberta.encoder.layer.6.attention.output.LayerNorm.bias', 'roberta.encoder.layer.6.output.LayerNorm.weight', 'roberta.encoder.layer.6.output.LayerNorm.bias', 'roberta.encoder.layer.7.attention.output.LayerNorm.weight', 'roberta.encoder.layer.7.attention.output.LayerNorm.bias', 'roberta.encoder.layer.7.output.LayerNorm.weight', 'roberta.encoder.layer.7.output.LayerNorm.bias', 'roberta.encoder.layer.8.attention.output.LayerNorm.weight', 'roberta.encoder.layer.8.attention.output.LayerNorm.bias', 'roberta.encoder.layer.8.output.LayerNorm.weight', 'roberta.encoder.layer.8.output.LayerNorm.bias', 'roberta.encoder.layer.9.attention.output.LayerNorm.weight', 'roberta.encoder.layer.9.attention.output.LayerNorm.bias', 'roberta.encoder.layer.9.output.LayerNorm.weight', 'roberta.encoder.layer.9.output.LayerNorm.bias', 'roberta.encoder.layer.10.attention.output.LayerNorm.weight', 'roberta.encoder.layer.10.attention.output.LayerNorm.bias', 'roberta.encoder.layer.10.output.LayerNorm.weight', 'roberta.encoder.layer.10.output.LayerNorm.bias', 'roberta.encoder.layer.11.attention.output.LayerNorm.weight', 'roberta.encoder.layer.11.attention.output.LayerNorm.bias', 'roberta.encoder.layer.11.output.LayerNorm.weight', 'roberta.encoder.layer.11.output.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.beta', 'roberta.embeddings.LayerNorm.gamma', 'roberta.encoder.layer.0.attention.output.LayerNorm.beta', 'roberta.encoder.layer.0.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.0.output.LayerNorm.beta', 'roberta.encoder.layer.0.output.LayerNorm.gamma', 'roberta.encoder.layer.1.attention.output.LayerNorm.beta', 'roberta.encoder.layer.1.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.1.output.LayerNorm.beta', 'roberta.encoder.layer.1.output.LayerNorm.gamma', 'roberta.encoder.layer.2.attention.output.LayerNorm.beta', 'roberta.encoder.layer.2.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.2.output.LayerNorm.beta', 'roberta.encoder.layer.2.output.LayerNorm.gamma', 'roberta.encoder.layer.3.attention.output.LayerNorm.beta', 'roberta.encoder.layer.3.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.3.output.LayerNorm.beta', 'roberta.encoder.layer.3.output.LayerNorm.gamma', 'roberta.encoder.layer.4.attention.output.LayerNorm.beta', 'roberta.encoder.layer.4.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.4.output.LayerNorm.beta', 'roberta.encoder.layer.4.output.LayerNorm.gamma', 'roberta.encoder.layer.5.attention.output.LayerNorm.beta', 'roberta.encoder.layer.5.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.5.output.LayerNorm.beta', 'roberta.encoder.layer.5.output.LayerNorm.gamma', 'roberta.encoder.layer.6.attention.output.LayerNorm.beta', 'roberta.encoder.layer.6.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.6.output.LayerNorm.beta', 'roberta.encoder.layer.6.output.LayerNorm.gamma', 'roberta.encoder.layer.7.attention.output.LayerNorm.beta', 'roberta.encoder.layer.7.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.7.output.LayerNorm.beta', 'roberta.encoder.layer.7.output.LayerNorm.gamma', 'roberta.encoder.layer.8.attention.output.LayerNorm.beta', 'roberta.encoder.layer.8.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.8.output.LayerNorm.beta', 'roberta.encoder.layer.8.output.LayerNorm.gamma', 'roberta.encoder.layer.9.attention.output.LayerNorm.beta', 'roberta.encoder.layer.9.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.9.output.LayerNorm.beta', 'roberta.encoder.layer.9.output.LayerNorm.gamma', 'roberta.encoder.layer.10.attention.output.LayerNorm.beta', 'roberta.encoder.layer.10.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.10.output.LayerNorm.beta', 'roberta.encoder.layer.10.output.LayerNorm.gamma', 'roberta.encoder.layer.11.attention.output.LayerNorm.beta', 'roberta.encoder.layer.11.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.11.output.LayerNorm.beta', 'roberta.encoder.layer.11.output.LayerNorm.gamma'].

Evaluating on Test Set...

=== FINAL HAUSA BASELINE RESULTS ===
F1-Macro: 0.6732
F1-Micro: 0.6763
Accuracy: 0.4731

In [15]:
# Check how many times each emotion appears in the training set
for i, col in enumerate(emotion_cols):
    count = sum([1 for x in tokenized_hausa['train']['labels'] if x[i] == 1.0])
    print(f"{col}: {count} positive examples")

anger: 408 positive examples
disgust: 329 positive examples
fear: 327 positive examples
joy: 320 positive examples
sadness: 647 positive examples
surprise: 349 positive examples

# Cell 13: Install Translation Dependencies  
We will need the sentencepiece library to handle NLLB’s tokenization.

In [16]:
!pip install sentencepiece

Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (0.2.1)

In [17]:
import torch
import gc

# Delete the old model and trainer to free up space
if 'model' in globals():
    del model
if 'trainer' in globals():
    del trainer

# Clear the cache
gc.collect()
torch.cuda.empty_cache()

print("GPU Memory Cleared!")

GPU Memory Cleared!

# Cell 14: Set up the NLLB Translation Pipeline  
We will use the "distilled" 600M version of NLLB. It is fast and fits easily in Google Colab's memory while providing high-quality translations.

In [18]:
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

model_name = "facebook/nllb-200-distilled-600M"

# Load model in float16 to save memory
model_nllb = AutoModelForSeq2SeqLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16
).to("cuda")

tokenizer_nllb = AutoTokenizer.from_pretrained(model_name)

def translate_nllb(text, tgt_lang_code):
    inputs = tokenizer_nllb(text, return_tensors="pt").to("cuda")

    tgt_lang_id = tokenizer_nllb.convert_tokens_to_ids(tgt_lang_code)

    translated_tokens = model_nllb.generate(
        **inputs,
        forced_bos_token_id=tgt_lang_id,
        max_length=400
    )

    return tokenizer_nllb.batch_decode(translated_tokens, skip_special_tokens=True)[0]

def back_translate(text):
    if not text or text.strip() == "":
        return text
    try:
        tokenizer_nllb.src_lang = "hau_Latn"
        pivot_text = translate_nllb(text, "eng_Latn")

        tokenizer_nllb.src_lang = "eng_Latn"
        augmented_text = translate_nllb(pivot_text, "hau_Latn")

        return augmented_text
    except Exception as e:
        return f"RETRY_ERROR: {str(e)}"

# TEST IT
test_text = "kotu ta yi hukunci kan shari'ar zaben dan majalisar pdp"
print(f"Test Result: {back_translate(test_text)}")

config.json:   0%|          | 0.00/846 [00:00<?, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

pytorch_model.bin:   0%|          | 0.00/2.46G [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.46G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/512 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie model.shared.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie model.shared.weight to model.decoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie model.shared.weight to model.encoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

generation_config.json:   0%|          | 0.00/189 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/564 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.3M [00:00<?, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

Test Result: Kotuna ne ke yanke hukunci kan dokar zabe da kuma majalisar PDP.

# Cell 15: Generate Augmented Data  
We will need to expand your dataset to 1.5x and 2x.

To get to 2x, we will back-translate every row in your training set.

We will only augment the Training Set. Never augment the Test set, as that would "leak" information and ruin your evaluation.

In [19]:
import pandas as pd
from tqdm import tqdm
tqdm.pandas() # For a progress bar

# Convert training set back to dataframe if it isn't already
df_hausa_train = hausa_dataset['train'].to_pandas()

print("Starting back-translation (this will take a few minutes)...")
# Apply back-translation to the text column
df_hausa_train['augmented_text'] = df_hausa_train['text'].progress_apply(back_translate)

# Create the augmented dataframe
# We keep the same labels but use the new augmented_text
df_augmented = df_hausa_train.copy()
df_augmented['text'] = df_augmented['augmented_text']
df_augmented = df_augmented.drop(columns=['augmented_text'])

# Combine original + augmented for the 2x dataset
df_hausa_2x = pd.concat([df_hausa_train.drop(columns=['augmented_text']), df_augmented], ignore_index=True)

print(f"Original size: {len(df_hausa_train)}")
print(f"Augmented size (Condition B - 2x): {len(df_hausa_2x)}")

Starting back-translation (this will take a few minutes)...

100%|██████████| 2145/2145 [31:09<00:00,  1.15it/s]

Original size: 2145
Augmented size (Condition B - 2x): 4290

# Cell 16: Prepare the Augmented Dataset for Training  
Now we convert this new dataframe back into a format the Hugging Face Trainer can use.

In [20]:
from datasets import Dataset, DatasetDict

# Convert the pandas dataframe back to a Hugging Face Dataset
hausa_2x_dataset = Dataset.from_pandas(df_hausa_2x)

# Re-tokenize the 2x dataset (using the same function from Cell 7)
tokenized_hausa_2x = hausa_2x_dataset.map(tokenize_function, batched=True)

# Format for PyTorch
tokenized_hausa_2x.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])

# Create a new DatasetDict using 'dev' instead of 'validation'
augmented_bundle = DatasetDict({
    'train': tokenized_hausa_2x,
    'dev': tokenized_hausa['dev'], # Changed from 'validation'
    'test': tokenized_hausa['test']
})

Map:   0%|          | 0/4290 [00:00<?, ? examples/s]

# Cell 17: Visual Check of Augmented Data  
Before training, it is crucial to verify that the back-translation actually changed the text while preserving the meaning.

In [21]:
from datasets import Dataset, DatasetDict

# 1. Re-convert the pandas dataframe (which should still be in memory)
hausa_2x_dataset = Dataset.from_pandas(df_hausa_2x)

# 2. Re-tokenize (Ensure tokenize_function is defined from Cell 7)
tokenized_hausa_2x = hausa_2x_dataset.map(tokenize_function, batched=True)

# 3. Format for PyTorch
tokenized_hausa_2x.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])

# 4. Re-create the bundle
augmented_bundle = DatasetDict({
    'train': tokenized_hausa_2x,
    'dev': tokenized_hausa['dev'],
    'test': tokenized_hausa['test']
})

print("Augmented bundle recreated! Ready to train.")

Map:   0%|          | 0/4290 [00:00<?, ? examples/s]

Augmented bundle recreated! Ready to train.

In [22]:
print("--- ORIGINAL HAUSA ---")
print(df_hausa_train['text'].iloc[0])

print("\n--- BACK-TRANSLATED HAUSA (Condition B) ---")
print(df_augmented['text'].iloc[0])

# Check if the labels remained consistent
print("\n--- LABELS (Should be identical) ---")
print(f"Original: {hausa_dataset['train'][0]['labels']}")
print(f"Augmented: {hausa_2x_dataset[len(df_hausa_train)]['labels']}")

--- ORIGINAL HAUSA ---
kotu ta yi hukunci kan shari'ar zaben dan majalisar pdp, ta yi hukuncin bazata

--- BACK-TRANSLATED HAUSA (Condition B) ---
Kotun ta yanke hukunci a kan batun zaben da kuma majalisar PDP, kuma ta yanke hukunci bisa ga hukuncin.

--- LABELS (Should be identical) ---
Original: [0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
Augmented: [0.0, 0.0, 0.0, 0.0, 0.0, 1.0]

# Cell 18: Re-initialize Model and Trainer for Condition B  
We must re-initialize the model to "reset" its brain. If we don't, we would be fine-tuning a model that already knows the test set, which is "cheating" (weight leakage).

In [23]:
#!rm -rf ./hausa_baseline_results
#!rm -rf ./hausa_aug_condition_b_results

In [24]:
from transformers import AutoModelForSequenceClassification, TrainingArguments, Trainer

# Reset the model to its pre-trained state (AfroXLMR-Base)
model_aug = AutoModelForSequenceClassification.from_pretrained(
    "Davlan/afro-xlmr-base",
    num_labels=6,
    problem_type="multi_label_classification"
)

# Use the same arguments as the baseline for a fair experiment
training_args_aug = TrainingArguments(
    output_dir='./hausa_aug_condition_b_results',
    eval_strategy="epoch",
    save_strategy="epoch",
    save_total_limit=2,             # ADD THIS: Only keep the 2 most recent/best models
    learning_rate=5e-5,
    lr_scheduler_type="cosine",
    per_device_train_batch_size=16,
    num_train_epochs=10,
    weight_decay=0.01,
    load_best_model_at_end=True,
    metric_for_best_model="f1_macro"
)

# Initialize the Trainer with the AUGMENTED training set
trainer_aug = Trainer(
    model=model_aug,
    args=training_args_aug,
    train_dataset=augmented_bundle['train'], # Using the 2x data here!
    eval_dataset=augmented_bundle['dev'],
    compute_metrics=compute_metrics # Using the function from Cell 9
)

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForSequenceClassification LOAD REPORT from: Davlan/afro-xlmr-base
Key                             | Status     |
--------------------------------+------------+-
lm_head.dense.bias              | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
classifier.out_proj.bias        | MISSING    |
classifier.dense.bias           | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [25]:
import torch
import gc

# Delete the translation model and tokenizer to free up space for training
if 'model_nllb' in globals():
    del model_nllb
if 'tokenizer_nllb' in globals():
    del tokenizer_nllb

# Clear the cache
gc.collect()
torch.cuda.empty_cache()

print("GPU space cleared! Ready to train Afro-XLMR.")

GPU space cleared! Ready to train Afro-XLMR.

# Cell 19: Train the Augmented Model  
This will take roughly twice as long as the baseline because the dataset is now double the size (~8-10 minutes on a T4 GPU).

In [26]:
print("Starting training on Augmented Hausa Data (Condition B - 2x)...")
trainer_aug.train()

Starting training on Augmented Hausa Data (Condition B - 2x)...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.weight', 'roberta.embeddings.LayerNorm.bias', 'roberta.encoder.layer.0.attention.output.LayerNorm.weight', 'roberta.encoder.layer.0.attention.output.LayerNorm.bias', 'roberta.encoder.layer.0.output.LayerNorm.weight', 'roberta.encoder.layer.0.output.LayerNorm.bias', 'roberta.encoder.layer.1.attention.output.LayerNorm.weight', 'roberta.encoder.layer.1.attention.output.LayerNorm.bias', 'roberta.encoder.layer.1.output.LayerNorm.weight', 'roberta.encoder.layer.1.output.LayerNorm.bias', 'roberta.encoder.layer.2.attention.output.LayerNorm.weight', 'roberta.encoder.layer.2.attention.output.LayerNorm.bias', 'roberta.encoder.layer.2.output.LayerNorm.weight', 'roberta.encoder.layer.2.output.LayerNorm.bias', 'roberta.encoder.layer.3.attention.output.LayerNorm.weight', 'roberta.encoder.layer.3.attention.output.LayerNorm.bias', 'roberta.encoder.layer.3.output.LayerNorm.weight', 'roberta.encoder.layer.3.output.LayerNorm.bias', 'roberta.encoder.layer.4.attention.output.LayerNorm.weight', 'roberta.encoder.layer.4.attention.output.LayerNorm.bias', 'roberta.encoder.layer.4.output.LayerNorm.weight', 'roberta.encoder.layer.4.output.LayerNorm.bias', 'roberta.encoder.layer.5.attention.output.LayerNorm.weight', 'roberta.encoder.layer.5.attention.output.LayerNorm.bias', 'roberta.encoder.layer.5.output.LayerNorm.weight', 'roberta.encoder.layer.5.output.LayerNorm.bias', 'roberta.encoder.layer.6.attention.output.LayerNorm.weight', 'roberta.encoder.layer.6.attention.output.LayerNorm.bias', 'roberta.encoder.layer.6.output.LayerNorm.weight', 'roberta.encoder.layer.6.output.LayerNorm.bias', 'roberta.encoder.layer.7.attention.output.LayerNorm.weight', 'roberta.encoder.layer.7.attention.output.LayerNorm.bias', 'roberta.encoder.layer.7.output.LayerNorm.weight', 'roberta.encoder.layer.7.output.LayerNorm.bias', 'roberta.encoder.layer.8.attention.output.LayerNorm.weight', 'roberta.encoder.layer.8.attention.output.LayerNorm.bias', 'roberta.encoder.layer.8.output.LayerNorm.weight', 'roberta.encoder.layer.8.output.LayerNorm.bias', 'roberta.encoder.layer.9.attention.output.LayerNorm.weight', 'roberta.encoder.layer.9.attention.output.LayerNorm.bias', 'roberta.encoder.layer.9.output.LayerNorm.weight', 'roberta.encoder.layer.9.output.LayerNorm.bias', 'roberta.encoder.layer.10.attention.output.LayerNorm.weight', 'roberta.encoder.layer.10.attention.output.LayerNorm.bias', 'roberta.encoder.layer.10.output.LayerNorm.weight', 'roberta.encoder.layer.10.output.LayerNorm.bias', 'roberta.encoder.layer.11.attention.output.LayerNorm.weight', 'roberta.encoder.layer.11.attention.output.LayerNorm.bias', 'roberta.encoder.layer.11.output.LayerNorm.weight', 'roberta.encoder.layer.11.output.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.beta', 'roberta.embeddings.LayerNorm.gamma', 'roberta.encoder.layer.0.attention.output.LayerNorm.beta', 'roberta.encoder.layer.0.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.0.output.LayerNorm.beta', 'roberta.encoder.layer.0.output.LayerNorm.gamma', 'roberta.encoder.layer.1.attention.output.LayerNorm.beta', 'roberta.encoder.layer.1.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.1.output.LayerNorm.beta', 'roberta.encoder.layer.1.output.LayerNorm.gamma', 'roberta.encoder.layer.2.attention.output.LayerNorm.beta', 'roberta.encoder.layer.2.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.2.output.LayerNorm.beta', 'roberta.encoder.layer.2.output.LayerNorm.gamma', 'roberta.encoder.layer.3.attention.output.LayerNorm.beta', 'roberta.encoder.layer.3.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.3.output.LayerNorm.beta', 'roberta.encoder.layer.3.output.LayerNorm.gamma', 'roberta.encoder.layer.4.attention.output.LayerNorm.beta', 'roberta.encoder.layer.4.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.4.output.LayerNorm.beta', 'roberta.encoder.layer.4.output.LayerNorm.gamma', 'roberta.encoder.layer.5.attention.output.LayerNorm.beta', 'roberta.encoder.layer.5.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.5.output.LayerNorm.beta', 'roberta.encoder.layer.5.output.LayerNorm.gamma', 'roberta.encoder.layer.6.attention.output.LayerNorm.beta', 'roberta.encoder.layer.6.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.6.output.LayerNorm.beta', 'roberta.encoder.layer.6.output.LayerNorm.gamma', 'roberta.encoder.layer.7.attention.output.LayerNorm.beta', 'roberta.encoder.layer.7.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.7.output.LayerNorm.beta', 'roberta.encoder.layer.7.output.LayerNorm.gamma', 'roberta.encoder.layer.8.attention.output.LayerNorm.beta', 'roberta.encoder.layer.8.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.8.output.LayerNorm.beta', 'roberta.encoder.layer.8.output.LayerNorm.gamma', 'roberta.encoder.layer.9.attention.output.LayerNorm.beta', 'roberta.encoder.layer.9.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.9.output.LayerNorm.beta', 'roberta.encoder.layer.9.output.LayerNorm.gamma', 'roberta.encoder.layer.10.attention.output.LayerNorm.beta', 'roberta.encoder.layer.10.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.10.output.LayerNorm.beta', 'roberta.encoder.layer.10.output.LayerNorm.gamma', 'roberta.encoder.layer.11.attention.output.LayerNorm.beta', 'roberta.encoder.layer.11.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.11.output.LayerNorm.beta', 'roberta.encoder.layer.11.output.LayerNorm.gamma'].

TrainOutput(global_step=2690, training_loss=0.15874180474689015, metrics={'train_runtime': 1940.4528, 'train_samples_per_second': 22.108, 'train_steps_per_second': 1.386, 'total_flos': 2821967414323200.0, 'train_loss': 0.15874180474689015, 'epoch': 10.0})

# Cell 20: Final Evaluation and Comparison  
Now, we compare the augmented performance against your 0.6655 baseline.

In [27]:
print("\nEvaluating Augmented Model on Test Set...")
aug_results = trainer_aug.evaluate(augmented_bundle['test'])

print("\n" + "="*30)
print("EXPERIMENT RESULTS: HAUSA")
print(f"Baseline F1-Macro:  0.6655")
print(f"Condition B (2x) F1-Macro: {aug_results['eval_f1_macro']:.4f}")
print("="*30)

improvement = aug_results['eval_f1_macro'] - 0.6655
if improvement > 0:
    print(f"Success! Augmentation improved the model by {improvement:.4f}")
else:
    print("No improvement. The model might need more diverse pivot languages or paraphrasing.")

Evaluating Augmented Model on Test Set...

==============================
EXPERIMENT RESULTS: HAUSA
Baseline F1-Macro:  0.6655
Condition B (2x) F1-Macro: 0.6677
==============================
Success! Augmentation improved the model by 0.0022

# Cell 21: Re-Load Translation Model & Define Condition C Engine

In [28]:
# Cell 21: Re-Load NLLB & Define Condition C Translation Engine
import torch
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

print("Re-loading NLLB Model for Condition C...")
model_name = "facebook/nllb-200-distilled-600M"
model_nllb = AutoModelForSeq2SeqLM.from_pretrained(model_name, torch_dtype=torch.float16).to("cuda")
tokenizer_nllb = AutoTokenizer.from_pretrained(model_name)

def translate_nllb_v2(text, src_lang_code, tgt_lang_code):
    tokenizer_nllb.src_lang = src_lang_code
    inputs = tokenizer_nllb(text, return_tensors="pt", padding=True, truncation=True, max_length=400).to("cuda")
    tgt_lang_id = tokenizer_nllb.convert_tokens_to_ids(tgt_lang_code)

    # Using sampling for paraphrasing effect
    translated_tokens = model_nllb.generate(
        **inputs,
        forced_bos_token_id=tgt_lang_id,
        max_length=400,
        do_sample=True,
        top_k=50,
        top_p=0.95
    )
    return tokenizer_nllb.batch_decode(translated_tokens, skip_special_tokens=True)[0]

def get_condition_c(text):
    if not text or text.strip() == "":
        return text, text
    try:
        # 1. French Pivot (Hausa -> French -> Hausa)
        french_pivot = translate_nllb_v2(text, "hau_Latn", "fra_Latn")
        back_from_french = translate_nllb_v2(french_pivot, "fra_Latn", "hau_Latn")

        # 2. Hausa Paraphrase (Hausa -> English -> Hausa with sampling)
        english_pivot = translate_nllb_v2(text, "hau_Latn", "eng_Latn")
        paraphrase_hau = translate_nllb_v2(english_pivot, "eng_Latn", "hau_Latn")

        return back_from_french, paraphrase_hau
    except Exception as e:
        return text, text # Fallback if it fails
print("Condition C Engine Ready!")

Re-loading NLLB Model for Condition C...

Loading weights:   0%|          | 0/512 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie model.shared.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie model.shared.weight to model.decoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie model.shared.weight to model.encoder.embed_tokens.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning

Condition C Engine Ready!

# Cell 22: Generate the Data & Separate into Distinct Conditions

In [29]:
# Cell 22: Generate and Organize Condition C & Condition D Datasets
import copy
import pandas as pd
from tqdm.auto import tqdm

print("Starting Data Generation Pipeline...")

french_aug_data = []
para_aug_data = []

# Iterating over the ORIGINAL training data
for _, row in tqdm(df_hausa_train.iterrows(), total=len(df_hausa_train)):
    fr_text, para_text = get_condition_c(row['text'])

    # Create French back-translated row
    fr_row = copy.deepcopy(row)
    fr_row['text'] = fr_text
    french_aug_data.append(fr_row)

    # Create Paraphrased row
    para_row = copy.deepcopy(row)
    para_row['text'] = para_text
    para_aug_data.append(para_row)

df_french = pd.DataFrame(french_aug_data)
df_para = pd.DataFrame(para_aug_data)

# === STRUCTURAL ISOLATION OF CONDITIONS ===

# Condition C (2x): Original (1x) + Paraphrased (1x)
df_hausa_cond_c = pd.concat([df_hausa_train, df_para], ignore_index=True)

# Condition D (4x): Original (1x) + English BT (1x) + French BT (1x) + Paraphrased (1x)
df_hausa_cond_d = pd.concat([df_hausa_train, df_augmented, df_french, df_para], ignore_index=True)

print(f"Condition C Dataset Size (Paraphrasing Only): {len(df_hausa_cond_c)} rows")
print(f"Condition D Dataset Size (Combined BT + Paraphrasing): {len(df_hausa_cond_d)} rows")

# Save backups
df_hausa_cond_c.to_csv("hausa_augmented_cond_c_paraphrase.csv", index=False)
df_hausa_cond_d.to_csv("hausa_augmented_cond_d_combined.csv", index=False)

Starting Data Generation Pipeline...

  0%|          | 0/2145 [00:00<?, ?it/s]

Condition C Dataset Size (Paraphrasing Only): 4290 rows
Condition D Dataset Size (Combined BT + Paraphrasing): 8580 rows

# Cell 23: Clear GPU Memory

In [30]:
# Cell 23: Clear GPU Memory before training
import gc

if 'model_nllb' in globals():
    del model_nllb
if 'tokenizer_nllb' in globals():
    del tokenizer_nllb

gc.collect()
torch.cuda.empty_cache()

print("GPU space cleared! Ready to train Afro-XLMR pipelines.")

GPU space cleared! Ready to train Afro-XLMR pipelines.

# Cell 24: Re-tokenize and Re-bundle Separate Pipelines

In [31]:
# Cell 24: Re-bundle Datasets for Condition C and Condition D Separately
from datasets import Dataset, DatasetDict

# 1. Prepare Condition C (Paraphrasing Only)
dataset_c = Dataset.from_pandas(df_hausa_cond_c)
tokenized_c = dataset_c.map(tokenize_function, batched=True)
tokenized_c.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])

bundle_cond_c = DatasetDict({
    'train': tokenized_c,
    'dev': tokenized_hausa['dev'],
    'test': tokenized_hausa['test']
})

# 2. Prepare Condition D (Combined)
dataset_d = Dataset.from_pandas(df_hausa_cond_d)
tokenized_d = dataset_d.map(tokenize_function, batched=True)
tokenized_d.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])

bundle_cond_d = DatasetDict({
    'train': tokenized_d,
    'dev': tokenized_hausa['dev'],
    'test': tokenized_hausa['test']
})

print("Datasets mapped and ready!")

Map:   0%|          | 0/4290 [00:00<?, ? examples/s]

Map:   0%|          | 0/8580 [00:00<?, ? examples/s]

Datasets mapped and ready!

# Cell 25: Train and Evaluate Condition C (Paraphrasing)

In [32]:
# Cell 25: Train and Evaluate Condition C (Paraphrasing Only)
from transformers import AutoModelForSequenceClassification, TrainingArguments, Trainer

print("--- TRAINING CONDITION C (PARAPHRASING ONLY) ---")
model_cond_c = AutoModelForSequenceClassification.from_pretrained(
    "Davlan/afro-xlmr-base", num_labels=6, problem_type="multi_label_classification"
)

training_args_c = TrainingArguments(
    output_dir='./hausa_cond_c_results',
    eval_strategy="epoch", save_strategy="epoch", save_total_limit=2,
    learning_rate=3e-5, lr_scheduler_type="cosine", per_device_train_batch_size=16,
    num_train_epochs=10, weight_decay=0.01, load_best_model_at_end=True, metric_for_best_model="f1_macro"
)

trainer_cond_c = Trainer(
    model=model_cond_c, args=training_args_c,
    train_dataset=bundle_cond_c['train'], eval_dataset=bundle_cond_c['dev'], compute_metrics=compute_metrics
)

trainer_cond_c.train()
cond_c_results = trainer_cond_c.evaluate(bundle_cond_c['test'])

--- TRAINING CONDITION C (PARAPHRASING ONLY) ---

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForSequenceClassification LOAD REPORT from: Davlan/afro-xlmr-base
Key                             | Status     |
--------------------------------+------------+-
lm_head.dense.bias              | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
classifier.out_proj.bias        | MISSING    |
classifier.dense.bias           | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.weight', 'roberta.embeddings.LayerNorm.bias', 'roberta.encoder.layer.0.attention.output.LayerNorm.weight', 'roberta.encoder.layer.0.attention.output.LayerNorm.bias', 'roberta.encoder.layer.0.output.LayerNorm.weight', 'roberta.encoder.layer.0.output.LayerNorm.bias', 'roberta.encoder.layer.1.attention.output.LayerNorm.weight', 'roberta.encoder.layer.1.attention.output.LayerNorm.bias', 'roberta.encoder.layer.1.output.LayerNorm.weight', 'roberta.encoder.layer.1.output.LayerNorm.bias', 'roberta.encoder.layer.2.attention.output.LayerNorm.weight', 'roberta.encoder.layer.2.attention.output.LayerNorm.bias', 'roberta.encoder.layer.2.output.LayerNorm.weight', 'roberta.encoder.layer.2.output.LayerNorm.bias', 'roberta.encoder.layer.3.attention.output.LayerNorm.weight', 'roberta.encoder.layer.3.attention.output.LayerNorm.bias', 'roberta.encoder.layer.3.output.LayerNorm.weight', 'roberta.encoder.layer.3.output.LayerNorm.bias', 'roberta.encoder.layer.4.attention.output.LayerNorm.weight', 'roberta.encoder.layer.4.attention.output.LayerNorm.bias', 'roberta.encoder.layer.4.output.LayerNorm.weight', 'roberta.encoder.layer.4.output.LayerNorm.bias', 'roberta.encoder.layer.5.attention.output.LayerNorm.weight', 'roberta.encoder.layer.5.attention.output.LayerNorm.bias', 'roberta.encoder.layer.5.output.LayerNorm.weight', 'roberta.encoder.layer.5.output.LayerNorm.bias', 'roberta.encoder.layer.6.attention.output.LayerNorm.weight', 'roberta.encoder.layer.6.attention.output.LayerNorm.bias', 'roberta.encoder.layer.6.output.LayerNorm.weight', 'roberta.encoder.layer.6.output.LayerNorm.bias', 'roberta.encoder.layer.7.attention.output.LayerNorm.weight', 'roberta.encoder.layer.7.attention.output.LayerNorm.bias', 'roberta.encoder.layer.7.output.LayerNorm.weight', 'roberta.encoder.layer.7.output.LayerNorm.bias', 'roberta.encoder.layer.8.attention.output.LayerNorm.weight', 'roberta.encoder.layer.8.attention.output.LayerNorm.bias', 'roberta.encoder.layer.8.output.LayerNorm.weight', 'roberta.encoder.layer.8.output.LayerNorm.bias', 'roberta.encoder.layer.9.attention.output.LayerNorm.weight', 'roberta.encoder.layer.9.attention.output.LayerNorm.bias', 'roberta.encoder.layer.9.output.LayerNorm.weight', 'roberta.encoder.layer.9.output.LayerNorm.bias', 'roberta.encoder.layer.10.attention.output.LayerNorm.weight', 'roberta.encoder.layer.10.attention.output.LayerNorm.bias', 'roberta.encoder.layer.10.output.LayerNorm.weight', 'roberta.encoder.layer.10.output.LayerNorm.bias', 'roberta.encoder.layer.11.attention.output.LayerNorm.weight', 'roberta.encoder.layer.11.attention.output.LayerNorm.bias', 'roberta.encoder.layer.11.output.LayerNorm.weight', 'roberta.encoder.layer.11.output.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.beta', 'roberta.embeddings.LayerNorm.gamma', 'roberta.encoder.layer.0.attention.output.LayerNorm.beta', 'roberta.encoder.layer.0.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.0.output.LayerNorm.beta', 'roberta.encoder.layer.0.output.LayerNorm.gamma', 'roberta.encoder.layer.1.attention.output.LayerNorm.beta', 'roberta.encoder.layer.1.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.1.output.LayerNorm.beta', 'roberta.encoder.layer.1.output.LayerNorm.gamma', 'roberta.encoder.layer.2.attention.output.LayerNorm.beta', 'roberta.encoder.layer.2.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.2.output.LayerNorm.beta', 'roberta.encoder.layer.2.output.LayerNorm.gamma', 'roberta.encoder.layer.3.attention.output.LayerNorm.beta', 'roberta.encoder.layer.3.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.3.output.LayerNorm.beta', 'roberta.encoder.layer.3.output.LayerNorm.gamma', 'roberta.encoder.layer.4.attention.output.LayerNorm.beta', 'roberta.encoder.layer.4.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.4.output.LayerNorm.beta', 'roberta.encoder.layer.4.output.LayerNorm.gamma', 'roberta.encoder.layer.5.attention.output.LayerNorm.beta', 'roberta.encoder.layer.5.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.5.output.LayerNorm.beta', 'roberta.encoder.layer.5.output.LayerNorm.gamma', 'roberta.encoder.layer.6.attention.output.LayerNorm.beta', 'roberta.encoder.layer.6.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.6.output.LayerNorm.beta', 'roberta.encoder.layer.6.output.LayerNorm.gamma', 'roberta.encoder.layer.7.attention.output.LayerNorm.beta', 'roberta.encoder.layer.7.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.7.output.LayerNorm.beta', 'roberta.encoder.layer.7.output.LayerNorm.gamma', 'roberta.encoder.layer.8.attention.output.LayerNorm.beta', 'roberta.encoder.layer.8.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.8.output.LayerNorm.beta', 'roberta.encoder.layer.8.output.LayerNorm.gamma', 'roberta.encoder.layer.9.attention.output.LayerNorm.beta', 'roberta.encoder.layer.9.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.9.output.LayerNorm.beta', 'roberta.encoder.layer.9.output.LayerNorm.gamma', 'roberta.encoder.layer.10.attention.output.LayerNorm.beta', 'roberta.encoder.layer.10.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.10.output.LayerNorm.beta', 'roberta.encoder.layer.10.output.LayerNorm.gamma', 'roberta.encoder.layer.11.attention.output.LayerNorm.beta', 'roberta.encoder.layer.11.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.11.output.LayerNorm.beta', 'roberta.encoder.layer.11.output.LayerNorm.gamma'].

# Cell 26: Train and Evaluate Condition D (Combined)

In [33]:
# Cell 26: Train and Evaluate Condition D (Combined BT + Paraphrasing)
import gc

# Clean memory from previous run
del model_cond_c, trainer_cond_c
gc.collect()
torch.cuda.empty_cache()

print("\n--- TRAINING CONDITION D (COMBINED BT + PARAPHRASING) ---")
model_cond_d = AutoModelForSequenceClassification.from_pretrained(
    "Davlan/afro-xlmr-base", num_labels=6, problem_type="multi_label_classification"
)

training_args_d = TrainingArguments(
    output_dir='./hausa_cond_d_results',
    eval_strategy="epoch", save_strategy="epoch", save_total_limit=2,
    learning_rate=3e-5, lr_scheduler_type="cosine", per_device_train_batch_size=16,
    num_train_epochs=10, weight_decay=0.01, load_best_model_at_end=True, metric_for_best_model="f1_macro"
)

trainer_cond_d = Trainer(
    model=model_cond_d, args=training_args_d,
    train_dataset=bundle_cond_d['train'], eval_dataset=bundle_cond_d['dev'], compute_metrics=compute_metrics
)

trainer_cond_d.train()
cond_d_results = trainer_cond_d.evaluate(bundle_cond_d['test'])

--- TRAINING CONDITION D (COMBINED BT + PARAPHRASING) ---

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForSequenceClassification LOAD REPORT from: Davlan/afro-xlmr-base
Key                             | Status     |
--------------------------------+------------+-
lm_head.dense.bias              | UNEXPECTED |
lm_head.dense.weight            | UNEXPECTED |
roberta.embeddings.position_ids | UNEXPECTED |
lm_head.layer_norm.bias         | UNEXPECTED |
lm_head.bias                    | UNEXPECTED |
lm_head.layer_norm.weight       | UNEXPECTED |
classifier.out_proj.bias        | MISSING    |
classifier.dense.bias           | MISSING    |
classifier.out_proj.weight      | MISSING    |
classifier.dense.weight         | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.weight', 'roberta.embeddings.LayerNorm.bias', 'roberta.encoder.layer.0.attention.output.LayerNorm.weight', 'roberta.encoder.layer.0.attention.output.LayerNorm.bias', 'roberta.encoder.layer.0.output.LayerNorm.weight', 'roberta.encoder.layer.0.output.LayerNorm.bias', 'roberta.encoder.layer.1.attention.output.LayerNorm.weight', 'roberta.encoder.layer.1.attention.output.LayerNorm.bias', 'roberta.encoder.layer.1.output.LayerNorm.weight', 'roberta.encoder.layer.1.output.LayerNorm.bias', 'roberta.encoder.layer.2.attention.output.LayerNorm.weight', 'roberta.encoder.layer.2.attention.output.LayerNorm.bias', 'roberta.encoder.layer.2.output.LayerNorm.weight', 'roberta.encoder.layer.2.output.LayerNorm.bias', 'roberta.encoder.layer.3.attention.output.LayerNorm.weight', 'roberta.encoder.layer.3.attention.output.LayerNorm.bias', 'roberta.encoder.layer.3.output.LayerNorm.weight', 'roberta.encoder.layer.3.output.LayerNorm.bias', 'roberta.encoder.layer.4.attention.output.LayerNorm.weight', 'roberta.encoder.layer.4.attention.output.LayerNorm.bias', 'roberta.encoder.layer.4.output.LayerNorm.weight', 'roberta.encoder.layer.4.output.LayerNorm.bias', 'roberta.encoder.layer.5.attention.output.LayerNorm.weight', 'roberta.encoder.layer.5.attention.output.LayerNorm.bias', 'roberta.encoder.layer.5.output.LayerNorm.weight', 'roberta.encoder.layer.5.output.LayerNorm.bias', 'roberta.encoder.layer.6.attention.output.LayerNorm.weight', 'roberta.encoder.layer.6.attention.output.LayerNorm.bias', 'roberta.encoder.layer.6.output.LayerNorm.weight', 'roberta.encoder.layer.6.output.LayerNorm.bias', 'roberta.encoder.layer.7.attention.output.LayerNorm.weight', 'roberta.encoder.layer.7.attention.output.LayerNorm.bias', 'roberta.encoder.layer.7.output.LayerNorm.weight', 'roberta.encoder.layer.7.output.LayerNorm.bias', 'roberta.encoder.layer.8.attention.output.LayerNorm.weight', 'roberta.encoder.layer.8.attention.output.LayerNorm.bias', 'roberta.encoder.layer.8.output.LayerNorm.weight', 'roberta.encoder.layer.8.output.LayerNorm.bias', 'roberta.encoder.layer.9.attention.output.LayerNorm.weight', 'roberta.encoder.layer.9.attention.output.LayerNorm.bias', 'roberta.encoder.layer.9.output.LayerNorm.weight', 'roberta.encoder.layer.9.output.LayerNorm.bias', 'roberta.encoder.layer.10.attention.output.LayerNorm.weight', 'roberta.encoder.layer.10.attention.output.LayerNorm.bias', 'roberta.encoder.layer.10.output.LayerNorm.weight', 'roberta.encoder.layer.10.output.LayerNorm.bias', 'roberta.encoder.layer.11.attention.output.LayerNorm.weight', 'roberta.encoder.layer.11.attention.output.LayerNorm.bias', 'roberta.encoder.layer.11.output.LayerNorm.weight', 'roberta.encoder.layer.11.output.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.beta', 'roberta.embeddings.LayerNorm.gamma', 'roberta.encoder.layer.0.attention.output.LayerNorm.beta', 'roberta.encoder.layer.0.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.0.output.LayerNorm.beta', 'roberta.encoder.layer.0.output.LayerNorm.gamma', 'roberta.encoder.layer.1.attention.output.LayerNorm.beta', 'roberta.encoder.layer.1.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.1.output.LayerNorm.beta', 'roberta.encoder.layer.1.output.LayerNorm.gamma', 'roberta.encoder.layer.2.attention.output.LayerNorm.beta', 'roberta.encoder.layer.2.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.2.output.LayerNorm.beta', 'roberta.encoder.layer.2.output.LayerNorm.gamma', 'roberta.encoder.layer.3.attention.output.LayerNorm.beta', 'roberta.encoder.layer.3.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.3.output.LayerNorm.beta', 'roberta.encoder.layer.3.output.LayerNorm.gamma', 'roberta.encoder.layer.4.attention.output.LayerNorm.beta', 'roberta.encoder.layer.4.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.4.output.LayerNorm.beta', 'roberta.encoder.layer.4.output.LayerNorm.gamma', 'roberta.encoder.layer.5.attention.output.LayerNorm.beta', 'roberta.encoder.layer.5.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.5.output.LayerNorm.beta', 'roberta.encoder.layer.5.output.LayerNorm.gamma', 'roberta.encoder.layer.6.attention.output.LayerNorm.beta', 'roberta.encoder.layer.6.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.6.output.LayerNorm.beta', 'roberta.encoder.layer.6.output.LayerNorm.gamma', 'roberta.encoder.layer.7.attention.output.LayerNorm.beta', 'roberta.encoder.layer.7.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.7.output.LayerNorm.beta', 'roberta.encoder.layer.7.output.LayerNorm.gamma', 'roberta.encoder.layer.8.attention.output.LayerNorm.beta', 'roberta.encoder.layer.8.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.8.output.LayerNorm.beta', 'roberta.encoder.layer.8.output.LayerNorm.gamma', 'roberta.encoder.layer.9.attention.output.LayerNorm.beta', 'roberta.encoder.layer.9.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.9.output.LayerNorm.beta', 'roberta.encoder.layer.9.output.LayerNorm.gamma', 'roberta.encoder.layer.10.attention.output.LayerNorm.beta', 'roberta.encoder.layer.10.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.10.output.LayerNorm.beta', 'roberta.encoder.layer.10.output.LayerNorm.gamma', 'roberta.encoder.layer.11.attention.output.LayerNorm.beta', 'roberta.encoder.layer.11.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.11.output.LayerNorm.beta', 'roberta.encoder.layer.11.output.LayerNorm.gamma'].

# Cell 27: Final Structured Experiment Report

In [34]:
# Cell 27: Final Structured Experiment Report
print("\n" + "="*45)
print("       FINAL EXPERIMENTAL RESULTS: HAUSA")
print("="*45)
print(f"Condition A: Baseline (No Aug)     |  0.6655")
print(f"Condition B: Back-Translation Only  |  0.6677")
print(f"Condition C: Paraphrasing Only      |  {cond_c_results['eval_f1_macro']:.4f}")
print(f"Condition D: Combined (BT + Para)   |  {cond_d_results['eval_f1_macro']:.4f}")
print("="*45)

# Analytics summary logic
if cond_d_results['eval_f1_macro'] > max(0.6677, cond_c_results['eval_f1_macro']):
    print("Conclusion: Combining strategies (Condition D) produces the most robust performance gains.")
elif cond_c_results['eval_f1_macro'] > 0.6677:
    print("Conclusion: Targeted paraphrasing outperforms back-translation variations.")
else:
    print("Conclusion: Syntactic variance via back-translation remains the optimal individual approach.")

=============================================
       FINAL EXPERIMENTAL RESULTS: HAUSA
=============================================
Condition A: Baseline (No Aug)     |  0.6655
Condition B: Back-Translation Only  |  0.6677
Condition C: Paraphrasing Only      |  0.6559
Condition D: Combined (BT + Para)   |  0.6641
=============================================
Conclusion: Syntactic variance via back-translation remains the optimal individual approach.